branches:
  only:
    - 'master'
    - 'rails-3.1'

rvm:
  - 1.8.7
  - ree
  - 1.9.2
  
env:
  - DB=sqlite
  - DB=mysql

bundler_args: "--without development production"
before_script: "./config/ci/before-travis.sh"
script: "bundle exec rake travis"

